"""Add tema_sorteado field to Sustanciacion model

Revision ID: 0e58ba0ac6d1
Revises: 354d4a00ef7e
Create Date: 2025-03-24 12:14:03.446119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e58ba0ac6d1'
down_revision = '354d4a00ef7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema_sorteado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.drop_column('tema_sorteado')

    # ### end Alembic commands ###
