"""add documentos_firmados_folder_id to concursos

Revision ID: 230615b55640
Revises: baa8f3df3061
Create Date: 2025-03-13 09:25:24.744635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230615b55640'
down_revision = 'baa8f3df3061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentos_firmados_folder_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('documentos_firmados_folder_id')

    # ### end Alembic commands ###
