"""add_id_designacion_mocovi_to_concursos

Revision ID: 310c50c5a7ff
Revises: b6ad73e53f7b
Create Date: 2025-03-13 20:43:36.677649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310c50c5a7ff'
down_revision = 'b6ad73e53f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_designacion_mocovi', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('id_designacion_mocovi')

    # ### end Alembic commands ###
