"""add_documentos_tribunal_table

Revision ID: 3697a42dcdf1
Revises: 4e68dd0e1f4b
Create Date: 2025-03-17 11:12:15.605823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3697a42dcdf1'
down_revision = '4e68dd0e1f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_tribunal', schema=None) as batch_op:
        batch_op.alter_column('miembro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_tribunal', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('miembro_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
