"""add_asignaturas_to_concursos

Revision ID: 3ab35e473846
Revises: 4d9fc7479ad0
Create Date: 2025-03-13 08:29:47.931945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3ab35e473846'
down_revision = '4d9fc7479ad0'
branch_labels = None
depends_on = None


def upgrade():
    # Get database connection and inspector
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('concursos')]
    
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        # Only add columns if they don't exist
        if 'asignaturas' not in columns:
            batch_op.add_column(sa.Column('asignaturas', sa.String(length=255), nullable=True))
        if 'expediente' not in columns:
            batch_op.add_column(sa.Column('expediente', sa.String(length=100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('expediente')
        batch_op.drop_column('asignaturas')
    # ### end Alembic commands ###
