"""remove abierta_determinada field

Revision ID: 6a441e6b69b3
Revises: df9ba4c547a9
Create Date: 2025-03-10 17:25:02.644054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a441e6b69b3'
down_revision = 'df9ba4c547a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('abierta_determinada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abierta_determinada', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
