"""add_file_id_to_documentos_concurso

Revision ID: 6b37be81ec30
Revises: merge_firma_count_heads
Create Date: 2025-03-18 15:18:57.678832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b37be81ec30'
down_revision = 'merge_firma_count_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_concurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_concurso', schema=None) as batch_op:
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
