"""Add drive_folder_id to concursos

Revision ID: 7adc46eff975
Revises: fd8619a552d6
Create Date: 2024-03-10 17:55:20.470487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '7adc46eff975'
down_revision = 'fd8619a552d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('concursos')]
    
    if 'drive_folder_id' not in columns:
        with op.batch_alter_table('concursos', schema=None) as batch_op:
            batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')
    # ### end Alembic commands ###
