"""add_reset_token_to_tribunal_miembros

Revision ID: 8d122393b9a5
Revises: a531a2eb5f9e
Create Date: 2025-03-18 08:09:00.624091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d122393b9a5'
down_revision = 'a531a2eb5f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
