"""add_virtual_link_to_sustanciacion

Revision ID: 9dcb6556b68e
Revises: ab15d57258d9
Create Date: 2025-03-13 19:34:28.793997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcb6556b68e'
down_revision = 'ab15d57258d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constitucion_virtual_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.drop_column('constitucion_virtual_link')

    # ### end Alembic commands ###
