"""add_resolution_numbers_to_concursos

Revision ID: a6d48eac8e2c
Revises: 3697a42dcdf1
Create Date: 2025-03-17 16:14:51.063504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d48eac8e2c'
down_revision = '3697a42dcdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nro_res_llamado_interino', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nro_res_llamado_regular', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nro_res_tribunal_regular', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('nro_res_tribunal_regular')
        batch_op.drop_column('nro_res_llamado_regular')
        batch_op.drop_column('nro_res_llamado_interino')

    # ### end Alembic commands ###
