"""Add committee and council info fields to concurso model

Revision ID: ab15d57258d9
Revises: 230615b55640
Create Date: 2025-03-13 14:10:50.954737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab15d57258d9'
down_revision = '230615b55640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_comision_academica', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('despacho_comision_academica', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sesion_consejo_directivo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_consejo_directivo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('despacho_consejo_directivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('despacho_consejo_directivo')
        batch_op.drop_column('fecha_consejo_directivo')
        batch_op.drop_column('sesion_consejo_directivo')
        batch_op.drop_column('despacho_comision_academica')
        batch_op.drop_column('fecha_comision_academica')

    # ### end Alembic commands ###
