"""add_sorteo_and_exposicion_virtual_links

Revision ID: b6ad73e53f7b
Revises: 9dcb6556b68e
Create Date: 2025-03-13 20:13:47.837895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ad73e53f7b'
down_revision = '9dcb6556b68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sorteo_virtual_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('exposicion_virtual_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.drop_column('exposicion_virtual_link')
        batch_op.drop_column('sorteo_virtual_link')

    # ### end Alembic commands ###
