"""add_postulantes_folder_id_to_concursos

Revision ID: baa8f3df3061
Revises: 3ab35e473846
Create Date: 2025-03-13 08:50:22.027260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa8f3df3061'
down_revision = '3ab35e473846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postulantes_folder_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('postulantes_folder_id')

    # ### end Alembic commands ###
