"""add_auth_fields_and_constraints

Revision ID: bf8de14c15e0
Revises: a6d48eac8e2c
Create Date: 2025-03-17 19:08:28.352214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8de14c15e0'
down_revision = 'a6d48eac8e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_documentos_postulante')
    with op.batch_alter_table('documentos_postulante', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('notificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_notificacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_acceso', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_tribunal_miembro_username', ['username'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tribunal_miembro_username', type_='unique')
        batch_op.drop_column('ultimo_acceso')
        batch_op.drop_column('fecha_notificacion')
        batch_op.drop_column('notificado')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('documentos_postulante', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('_alembic_tmp_documentos_postulante',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('postulante_id', sa.INTEGER(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('creado', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['postulante_id'], ['postulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
