"""Add drive_folder_id to postulantes

Revision ID: caa7746b04ac
Revises: 7adc46eff975
Create Date: 2024-03-10 18:05:20.470487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'caa7746b04ac'
down_revision = '7adc46eff975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('postulantes')]
    
    if 'drive_folder_id' not in columns:
        with op.batch_alter_table('postulantes', schema=None) as batch_op:
            batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulantes', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')
    # ### end Alembic commands ###
