"""add_temas_exposicion_to_sustanciacion

Revision ID: d99133a37629
Revises: f590ac8bca40
Create Date: 2025-03-17 09:20:05.294230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99133a37629'
down_revision = 'f590ac8bca40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temas_exposicion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustanciacion', schema=None) as batch_op:
        batch_op.drop_column('temas_exposicion')

    # ### end Alembic commands ###
