"""Make cierre_inscripcion nullable

Revision ID: df9ba4c547a9
Revises: 
Create Date: 2025-03-10 17:07:44.874491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9ba4c547a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.alter_column('cierre_inscripcion',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.alter_column('cierre_inscripcion',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
