"""add_sustanciacion_notification_fields

Revision ID: f22b738c5585
Revises: 8d122393b9a5
Create Date: 2025-03-18 09:18:08.752650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22b738c5585'
down_revision = '8d122393b9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificado_sustanciacion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_notificacion_sustanciacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribunal_miembros', schema=None) as batch_op:
        batch_op.drop_column('fecha_notificacion_sustanciacion')
        batch_op.drop_column('notificado_sustanciacion')

    # ### end Alembic commands ###
