"""add_categoria_and_dedicacion_vacante_to_concursos

Revision ID: f590ac8bca40
Revises: 310c50c5a7ff
Create Date: 2025-03-13 20:47:47.845114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f590ac8bca40'
down_revision = '310c50c5a7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_vacante', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dedicacion_vacante', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('dedicacion_vacante')
        batch_op.drop_column('categoria_vacante')

    # ### end Alembic commands ###
