"""add_borradores_folder_id_to_concursos

Revision ID: f83307e6cd84
Revises: caa7746b04ac
Create Date: 2025-03-12 13:42:56.060057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83307e6cd84'
down_revision = 'caa7746b04ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borradores_folder_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('borradores_folder_id')

    # ### end Alembic commands ###
