"""add categoria_nombre to concursos

Revision ID: fd8619a552d6
Revises: 6a441e6b69b3
Create Date: 2025-03-10 17:45:30.470487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'fd8619a552d6'
down_revision = '6a441e6b69b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('concursos')]
    
    if 'categoria_nombre' not in columns:
        with op.batch_alter_table('concursos', schema=None) as batch_op:
            batch_op.add_column(sa.Column('categoria_nombre', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('categoria_nombre')
    # ### end Alembic commands ###
